<a href="https://colab.research.google.com/github/HarshXtech/Datasets/blob/main/backpropogation_in_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
data = {
    'cgpa' : [8, 7, 6, 5],
    'resume_score' : [8, 9, 10, 12],
    'lpa' : [4,5,6,7]
}

df = pd.DataFrame(data)

In [3]:
df

cgpa  resume_score  lpa
0     8             8    4
1     7             9    5
2     6            10    6
3     5            12    7

In [23]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [24]:
model = Sequential()

In [25]:
model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [26]:
model.get_weights()

[array([[-0.43860972, -0.90902656],
        [ 0.93836033, -0.8530586 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.07534409],
        [-0.15459871]], dtype=float32),
 array([0.], dtype=float32)]

In [35]:
new_weights = [


np.array([[0.1, 0.1],
        [0.1, 0.1]]),
 np.array([0. , 0.]),
 np.array([[0.1],
        [0.1]]),
np.array([0.])
]


In [36]:
model.set_weights(new_weights)

In [37]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [38]:
model.fit(df.iloc[:, :-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 28.7064
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 27.1781
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.0235
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.7301
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 25.3950 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 23.8409 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31.4006 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 25.0722 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.3481 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 24.2500 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 23.1486 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 27.4392
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 28.6646
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 23.2270
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 27.2094
Epoch 16/75


In [39]:
model.get_weights()

[array([[0.37358508, 0.37358508],
        [0.36558127, 0.36558127]], dtype=float32),
 array([0.27228025, 0.27228025], dtype=float32),
 array([[0.37288812],
        [0.37288812]], dtype=float32),
 array([0.20472471], dtype=float32)]